users = 300
spawn-rate = 30
run-time = 3m
headless = true
locustfile= ./scenarios/grpc/gateway/existing_user_make_purchase_operation/scenario.py
html = ./scenarios/grpc/gateway/existing_user_make_purchase_operation/report.html